# Generated by Django 5.1.6 on 2025-07-21 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro_th', models.CharField(max_length=255)),
                ('name_pro_en', models.CharField(max_length=255)),
                ('case_stu', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=50)),
                ('school_y', models.CharField(max_length=10)),
                ('adviser', models.CharField(max_length=255)),
                ('co_advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('strategic', models.TextField()),
                ('plan', models.TextField()),
                ('key_result', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sp_project',
            },
        ),
        migrations.CreateModel(
            name='SpProjectAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='backend.spproject')),
            ],
            options={
                'db_table': 'sp_project_author',
            },
        ),
    ]
