# Generated by Django 5.2.4 on 2025-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_spproject_spprojectauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCover',
            fields=[
                ('cover_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name_th', models.CharField(max_length=500, null=True)),
                ('project_name_en', models.CharField(max_length=500, null=True)),
                ('author1_name_th', models.CharField(max_length=255, null=True)),
                ('author2_name_th', models.CharField(max_length=255, null=True)),
                ('author1_name_en', models.CharField(max_length=255, null=True)),
                ('author2_name_en', models.CharField(max_length=255, null=True)),
                ('academic_year', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'doc_cover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('abstract_id', models.AutoField(primary_key=True, serialize=False)),
                ('author1_th', models.CharField(max_length=255)),
                ('author1_en', models.CharField(max_length=255)),
                ('author2_th', models.CharField(max_length=255)),
                ('author2_en', models.CharField(max_length=255)),
                ('project_name_th', models.CharField(max_length=255)),
                ('project_name_en', models.CharField(max_length=255)),
                ('abstract_th', models.TextField()),
                ('abstract_en', models.TextField()),
                ('major_th', models.CharField(max_length=255)),
                ('major_en', models.CharField(max_length=255)),
                ('advisor_th', models.CharField(max_length=255)),
                ('advisor_en', models.CharField(max_length=255)),
                ('coadvisor_th', models.CharField(max_length=255)),
                ('coadvisor_en', models.CharField(max_length=255)),
                ('academic_year_th', models.IntegerField()),
                ('academic_year_en', models.IntegerField()),
                ('keyword_th', models.CharField(max_length=255)),
                ('keyword_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'abstract',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='spprojectauthor',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='spproject',
            name='bg_and_sig_para1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spproject',
            name='bg_and_sig_para2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spproject',
            name='bg_and_sig_para3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='spproject',
            name='purpose_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='spproject',
            name='purpose_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='spproject',
            name='purpose_3',
            field=models.CharField(default='', max_length=255),
        ),
    ]
